import '@/styles/globals.css';
import { Navigation } from '@/Comps/Nav/navigation';
import { MyFooter } from '@/Comps/Footer/footer';

const isVercel = process.env.VERCEL === '1';

export const metadata = {
 title: "Url Title",
 description: "Generated by create next app",
 icons: { icon: isVercel ? '/red.ico' : '/next5/red.ico' }
};

export default function RootLayout({ children }) {
 return (
  <html lang="en">
   <body>
    <header className="">
     <p className="text-3xl font-bold text-red-600">Welcome to my site!</p>
     <Navigation />
    </header>
    {children}
    <MyFooter />
   </body>
  </html>
 );
}
