/*Dashboard\layout.js*/
export const metadata = {
 title: "Dashboard",
 description: "Generated by create next app",
};

export default function DashboardRootLayout({ children }) {
 return (
  <>
   <header className="bg-slate-400 text-white text-center">
    <p>Dashboard Header</p>
   </header>
   {children}
   <footer className="bg-amber-300 text-white text-center">
    <p>Dashboard Footer</p>
   </footer>
  </>
 );
}